#!/bin/bash
##script requires: 
##dig 
##mail server with mail function (if chosen use_smtp="0")
##mailx (if chosen use_smtp="1")


#sleep between subnets
ssub=2s
#sleep between each ip is checked
sip=0.1s
#sleep between each blacklist check
sblck=0.001s
#Email to witch one it will send blacklisted ip
EMAIL="info@email.com"
#Send email after each subnet check 1 = yes; 0 =  email will be send instantly after blaclist found
semail=1

#prompter, if 1 then in email will be included remooval link from file suf
prompter=1
prompter_phone=111111
prompter_email=$EMAIL #you can enter any other email if you want


use_smtp="0" # requires package mailx if 1 then emails will be sent via smtp if 0 via mail server
smtp_srv="smt.server.com"
smtp_port="25"
smtp_user="smtp_user@server.com"
smtp_password="smtp_password"
smtp_from="from@server.com"
smtp_ssl_args="-S smtp-use-starttls -S nss-config-dir=/etc/pki/nssdb/ -S ssl-verify=ignore"

if [ "$semail" = 1  ]; then
	declare -a mailarr
fi

while read i;
do
	i1=`echo $i | awk '{print $1}'`
	i2=`echo $i | awk '{print $2}'`
	i3=`echo $i | awk '{print $3}'`
	while [[ $i2 -le $i3 ]]
	do
		ip=`echo $i1.$i2 |awk -F"." '{for(i=NF;i>0;i--) printf i!=1?$i".":"%s",$i}'`
		for l in $(cat list | grep -v "#")
		do
			res=`dig +short $ip.$l | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep 127.0.*`
			if [ ! -z "$res"  ]; then
				if [ "$prompter" = 1  ]; then
					rez_prompter=`cat prompter | grep -v "#" | grep $l | awk '{print $2}' |  sed "s/{{ip}}/$i1.$i2/g" | sed "s/{{phone}}/$prompter_phone/g" | sed "s/{{email}}/$prompter_email/g"`
					if [ ! -z "$rez_prompter"  ]; then
						EMAILMESSAGE=`echo " ip $i1.$i2 blacklisted on $l list - gotten result $res\n $rez_prompter\n\n"`
					else
						EMAILMESSAGE=`echo " ip $i1.$i2 blacklisted on $l list - gotten result $res\n\n"`
					fi
				else
					EMAILMESSAGE=`echo " ip $i1.$i2 blacklisted on $l list - gotten result $res\n"`
				fi
				if [ ! -z "$EMAIL"  ]; then #do not send email if dont want it
					if [ "$semail" = 0  ]; then
						if [ "$use_smtp" = 1  ]; then
							echo -e $EMAILMESSAGE | mailx -s "BLACKLISTED ips $i1" $smtp_ssl_args -S smtp=smtp://$smtp_srv:$smtp_port -S smtp-auth=login -S smtp-auth-user=$smtp_user -S smtp-auth-password=$smtp_password -S from="Sender Name <$smtp_from>" $EMAIL
						else
							echo -e $EMAILMESSAGE | mail -s "BLACKLISTED ips $i1" "$EMAIL"
						fi   
					else
						mailarr+=($EMAILMESSAGE)
					fi
				fi
				echo $EMAILMESSAGE
			else
				echo "ip $i1.$i2 not blacklisted on $l list - gotten result $res"
			fi
			sleep $sblck
		done
		((i2 = i2 + 1))
		sleep $sip
	done
	if [ "$semail" = 1  ]; then
		if [ -z "$mailarr" ]; then
			echo "Array empty"
		else
			if [ "$use_smtp" = 1  ]; then
				echo -e  ${mailarr[*]} | mailx -s "BLACKLISTED ips $i1" $smtp_ssl_args -S smtp=smtp://$smtp_srv:$smtp_port -S smtp-auth=login -S smtp-auth-user=$smtp_user -S smtp-auth-password=$smtp_password -S from="Sender Name <$smtp_from>" $EMAIL
			else
				echo -e  ${mailarr[*]} | mail -s "BLACKLISTED ips $i1" "$EMAIL"
			fi   
		fi
		unset mailarr
	fi
sleep $ssub
done <sub
