#!/bin/bash
#sleep between subnets
ssub=2s
#sleep between each ip is checked
sip=0.1s
#sleep between each blacklist check
sblck=0.001s
#Email to witch one it will send blacklisted ip
EMAIL="info@email.com"
#Send email after each subnet check 1 = yes; 0 =  email will be send instantly after blaclist found
semail=1

if [ "$semail" = 1  ]; then
  declare -a mailarr
fi

while read i;
do
  i1=`echo $i | awk '{print $1}'`
  i2=`echo $i | awk '{print $2}'`
  i3=`echo $i | awk '{print $3}'`
  while [[ $i2 -le $i3 ]]
  do
  ip=`echo $i1.$i2 |awk -F"." '{for(i=NF;i>0;i--) printf i!=1?$i".":"%s",$i}'`
   for l in $(cat list | grep -v "#")
   do
    res=`dig +short $ip.$l | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep 127.0.*`
    if [ ! -z "$res"  ]; then
    EMAILMESSAGE=`echo "ip $i1.$i2 blacklisted on $l list - gotten result $res \n"`
    if [ ! -z "$EMAIL"  ]; then #do not send email if dont want it
    if [ "$semail" = 0  ]; then
           echo -e $EMAILMESSAGE | mail -s "BLACKLISTED ip" "$EMAIL"
    else
          mailarr+=($EMAILMESSAGE)
    fi
    fi
    echo $EMAILMESSAGE
    else
    echo "ip $i1.$i2 not blacklisted on $l list - gotten result $res"
    fi
    sleep $sblck
   done
  ((i2 = i2 + 1))
   sleep $sip
  done
  if [ "$semail" = 1  ]; then
  echo -e  ${mailarr[*]} | mail -s "BLACKLISTED ips $i1" "$EMAIL"
  unset mailarr
  fi
 sleep $ssub
done <sub
